a=10
b=20
print("a>b",a>b)
print("a<b",a>b)
print("a>=b",a>=b)
print("a<=b",a<=b)
print("a!=b",a!=b)
print("a==b",a==b)
c=30
d=20
print("\nb==d",b==d)
print("b!=d",b!=d)
print("b<=d",b<=d)
print("b>=d",b>=d)
print(a>c)
print(a<c)
print(a<=c)
print(a>=c)
print(a!=c)
print(a==c)
print("\n",a<d)
print(a>d)
print(a>=d)
print(a<=d)